In [1]:
from transformers import AutoTokenizer,AutoModelForCausalLM

In [2]:
tokenizer = AutoTokenizer.from_pretrained('distilgpt2')

C:\Users\dany\.conda\envs\tfm\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [3]:
model = AutoModelForCausalLM.from_pretrained('distilgpt2',output_hidden_states=True)

In [13]:
text = 'kabhi khushi'

In [14]:
input = tokenizer.encode(text,return_tensors='pt')

In [15]:
input

tensor([[   74,   397,  5303, 44081, 17731]])

In [17]:
output = model.generate(input,max_length=7,do_sample=False)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [18]:
output

tensor([[   74,   397,  5303, 44081, 17731,   479,   283]])

In [19]:
print('\n',tokenizer.decode(output[0]))


 kabhi khushi kar


In [20]:
output

tensor([[   74,   397,  5303, 44081, 17731,   479,   283]])

In [21]:
output[0]

tensor([   74,   397,  5303, 44081, 17731,   479,   283])

In [22]:
input = tokenizer(text,return_tensors='pt')['input_ids']

In [23]:
input

tensor([[   74,   397,  5303, 44081, 17731]])

In [24]:
tokenizer.convert_ids_to_tokens(input[0])

['k', 'ab', 'hi', 'Ġkh', 'ushi']

In [25]:
model.transformer.wte

Embedding(50257, 768)

In [27]:
import torch

In [28]:
model.transformer.wte(torch.tensor(5303))

tensor([-8.3567e-02, -3.5492e-02,  8.9526e-02, -8.3440e-03,  1.2213e-01,
         2.6488e-01, -2.7583e-01, -8.4173e-02,  9.3775e-02,  2.7267e-01,
        -1.3663e-01,  9.4392e-02, -5.4182e-02,  5.2010e-02,  1.2742e-01,
         2.0699e-01,  8.9082e-02,  2.3076e-02,  2.5875e-01,  1.0278e-01,
         5.1171e-02, -3.8042e-02,  2.8455e-01,  4.5802e-01,  2.0700e-01,
        -8.0535e-02, -5.1844e-02,  9.7817e-02,  4.0818e-03, -3.2785e-03,
        -3.3026e-01, -3.8533e-01,  2.8358e-02,  7.8176e-02, -2.1908e-01,
         1.5113e-01, -3.1548e-01, -2.1689e-03, -3.6411e-02,  5.6203e-02,
         4.1375e-02,  7.1746e-02, -1.2743e-01, -1.1555e-01, -9.3855e-02,
        -1.5175e-01, -1.5064e-02,  1.9065e-01,  8.3905e-02,  3.9262e-03,
        -8.8730e-03, -3.0980e-03, -2.1613e-02, -7.0700e-02, -5.0771e-02,
        -3.0079e-02, -2.1463e-01,  5.0632e-02,  8.2793e-02, -7.9612e-03,
        -5.3502e-02,  2.9217e-01, -2.6620e-01,  1.3850e-01,  1.6574e-01,
         2.4321e-02, -1.1191e-01, -1.8630e-01,  1.7

In [31]:
text = 'The chiken did not cross the road because it was'

In [32]:
input = tokenizer.encode(text,return_tensors='pt')

In [33]:
input

tensor([[  464,   442, 29943,   750,   407,  3272,   262,  2975,   780,   340,
           373]])

In [49]:
output = model.generate(input,max_length=30,do_sample=True)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [50]:
output

tensor([[  464,   442, 29943,   750,   407,  3272,   262,  2975,   780,   340,
           373,   257,   845,  8468,   779,    13,   198,   464,   442, 29943,
           373,   407,   257,  3704,   286,  3348,   475,   257,  3912,    11]])

In [51]:
print('\n',tokenizer.decode(output[0]))


 The chiken did not cross the road because it was a very unusual use.
The chiken was not a piece of paper but a pattern,
